name: Connect to SSH and Keep Alive with tmux

on:
  workflow_dispatch:

jobs:
  ssh-connect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install sshpass and tmux
      run: |
        apt-get update && apt-get install -y sshpass tmux

    - name: Run SSH Connection Script
      run: |
        bash connect_ssh.sh
      continue-on-error: true
