name: Connect to SSH and Keep Alive with tmux

on:
  workflow_dispatch:

jobs:
  ssh-connect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: remove lock file
      run: sudo rm /var/lib/dpkg/lock-frontend && sudo rm /var/lib/dpkg/lock

    - name: Install sshpass and tmux
      run: sudo apt-get update && apt-get install -y sshpass tmux

    - name: Run SSH Connection Script
      run: sudo bash connect_ssh.sh
      continue-on-error: true
